import { Inter } from 'next/font/google'
import './globals.css'

import './Hero.scss';
import './Hero-media.scss';

import './NavBar.scss';
import './Navbar-media.scss';
import './Terminal.scss';
import './Terminal-media.scss';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          defer
          src="https://b.stripecdn.com/site-srv/assets/compiled/js/blog/globe-f22b76d7dcb05af683c3.min.js"
        ></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
